CREATE DATABASE cashRegisterDB;
USE cashRegisterDB;

CREATE TABLE company (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    image VARCHAR(100),
    billMessage VARCHAR(255),
    homeDelivery BOOLEAN NOT NULL DEFAULT false,
    visible BOOLEAN NOT NULL DEFAULT false,
    active BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE role (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE user (
    idCompany INT NOT NULL,
    idRole INT NOT NULL,
    CONSTRAINT fkCompanyUser FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fkRoleUser FOREIGN KEY (idRole) REFERENCES role (id) ON DELETE CASCADE ON UPDATE CASCADE,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE category (
    idCompany INT NOT NULL,
    CONSTRAINT fkCompanyCategory FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE products (
    idCompany INT NOT NULL,
    idCategory INT NOT NULL,
    CONSTRAINT fkCompanyProduct FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fkCategoriyProduct FOREIGN KEY (idCategory) REFERENCES category (id) ON DELETE CASCADE ON UPDATE CASCADE,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    price INT NOT NULL DEFAULT 0,
    description VARCHAR(255),
	image VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE ingredients (
    idCompany INT NOT NULL,
    CONSTRAINT fkCompanyIngredient FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    priceByUnit FLOAT NOT NULL,
    amount INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE detailProductsIngredients (
    idCompany INT NOT NULL,
    idProduct INT NOT NULL,
    idIngredient INT NOT NULL,
    CONSTRAINT fkCompany FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fkIngredients FOREIGN KEY (idIngredient) REFERENCES ingredients (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fkProducts FOREIGN KEY (idProduct) REFERENCES products (id) ON DELETE CASCADE ON UPDATE CASCADE,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    spendingAmount INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE clients (
    idCompany INT NOT NULL,
    CONSTRAINT fkCompanyClient FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    address VARCHAR(30),
    phoneNumber VARCHAR(15),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE bills (
    idCompany INT NOT NULL,
    idClient INT NOT NULL,
    CONSTRAINT fkCompanyBill FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fkClientBill FOREIGN KEY (idClient) REFERENCES clients (id) ON DELETE CASCADE ON UPDATE CASCADE,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    total INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    homeDelivery INT
);

CREATE TABLE productsInBills (
    idCompany INT NOT NULL,
    idBill INT NOT NULL,
    CONSTRAINT fkCompanyProductsInBills FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fkBills FOREIGN KEY (idBill) REFERENCES bills (id) ON DELETE CASCADE ON UPDATE CASCADE,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    price INT NOT NULL,
    amount INT NOT NULL
);

SHOW TABLES;

-- Before this run user.sql or change the keys.ts document.