CREATE DATABASE cashRegisterDB;
USE cashRegisterDB;

CREATE TABLE company (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    image VARCHAR(255),
    billMessage VARCHAR(255),
    homeDelivery BOOLEAN NOT NULL DEFAULT false,
    visible BOOLEAN NOT NULL DEFAULT false,
    active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE role (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE user (
    idCompany INT NOT NULL,
    idRole INT NOT NULL,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT fkCompanyUser FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fkRoleUser FOREIGN KEY (idRole) REFERENCES role (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE category (
    idCompany INT NOT NULL,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT fkCompanyCategory FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE product (
    idCompany INT NOT NULL,
    idCategory INT NOT NULL,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    price INT NOT NULL DEFAULT 0,
    description VARCHAR(255),
	image VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT fkCategoryProduct FOREIGN KEY (idCategory) REFERENCES category (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fkCompanyProduct FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ingredient (
    idCompany INT NOT NULL,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    priceByUnit FLOAT NOT NULL,
    amount INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT fkCompanyIngredient FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE productsHasIngredients (
    idCompany INT NOT NULL,
    idProduct INT NOT NULL,
    idIngredient INT NOT NULL,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    spendingAmount INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT fkCompany FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fkIngredient FOREIGN KEY (idIngredient) REFERENCES ingredient (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fkProduct FOREIGN KEY (idProduct) REFERENCES product (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE client (
    idCompany INT NOT NULL,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    address VARCHAR(30),
    phoneNumber VARCHAR(15),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT fkCompanyClient FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE bill (
    idCompany INT NOT NULL,
    idClient INT NOT NULL,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    total INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    homeDelivery INT,
    CONSTRAINT fkCompanyBill FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fkClientBill FOREIGN KEY (idClient) REFERENCES client (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE billsHasProducts (
    idCompany INT NOT NULL,
    idBill INT NOT NULL,
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    price INT NOT NULL,
    amount INT NOT NULL,
    CONSTRAINT fkCompanyBillProduct FOREIGN KEY (idCompany) REFERENCES company (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fkBill FOREIGN KEY (idBill) REFERENCES bill (id) ON DELETE CASCADE ON UPDATE CASCADE
);

SHOW TABLES;

-- Before this run user.sql or change the keys.ts document.